
ref_dir: refdata-cellranger-arc-GRCh38-2020-A-2.0.0
cores: 26
mem: 64
fastq_dir: fastqs                                                     
fastq_ext: .fastq.gz                                                 
out_dir: outputs                                                        
bbduk_path: bbmap/bbduk.sh                                              
cellranger_path: cellranger-atac-2.1.0/cellranger-atac                  
